### ISSUE TITLE
Event Driven Architecture in Golang Building complex

### ISSUE THREAD

**Issue by alirezaarzehgar** [alirezaarzehgar/alirezaarzehgar#18]
Pages: 384

# Part 1: Event-Driven Fundamentals
- [ ] 1 Introduction to Event-Driven Architectures
- [ ] 2 Supporting Patterns in Brief
- [ ] 3 Design and Planning
 
# Part 2: Components of Event-Driven Architecture
- [ ] 4 Event Foundations
- [ ] 5 Tracking Changes with Event Sourcing
- [ ] 6 Asynchronous Connections
- [ ] 7 Event-Carried State Transfer
- [ ] 8 Message Workflows
- [ ] 9 Transactional Messaging

# Part 3: Production Ready
- [ ] 10 Testing
- [ ] 11 Deploying Applications to the Cloud
- [ ] 12 Monitoring and Observability
