### ISSUE TITLE
Prometheus Up & Running 

### ISSUE THREAD

**Issue by alirezaarzehgar** [alirezaarzehgar/alirezaarzehgar#4]
Pages: 386
# INFRASTRUCTURE AND APPLICATION PERFORMANCE MONITORING

## Part I. Introduction
- [ ] 1. What Is Prometheus?
- [ ] 2. Getting Started with Prometheus
## Part II. Application Monitoring
- [ ] 3. Instrumentation
- [ ] 4. Exposition
- [ ] 5. Labels
- [ ] 6. Dashboarding with Grafana
## Part III. Infrastructure Monitoring
- [ ] 7. Node Exporter
- [ ] 8. Service Discovery
- [ ] 9. Containers and Kubernetes
- [ ] 10. Common Exporters
- [ ] 11. Working with Other Monitoring Systems
- [ ] 12. Writing Exporters
## Part IV. PromQL
- [ ] 13. Introduction to PromQL
- [ ] 14. Aggregation Operators
- [ ] 15. Binary Operators
- [ ] 16. Functions
- [ ] 17. Recording Rules
## Part V. Alerting
- [ ] 18. Alerting
- [ ] 19. Alertmanager
## Part VI. Deployment
- [ ] 20. Putting It All Together
