### ISSUE TITLE
Mastering Kafka Streams and ksqlDB

### ISSUE THREAD

**Issue by alirezaarzehgar** [alirezaarzehgar/alirezaarzehgar#9]
Pages: 436
#  Building Real-Time Data Systems by Example

## Part I. Kafka
- [x] 1. A Rapid Introduction to Kafka
## Part II. Kafka Streams
- [ ] 2. Getting Started with Kafka Streams
- [ ] 3. Stateless Processing
- [ ] 4. Stateful Processing
- [ ] 5. Windows and Time
- [ ] 6. Advanced State Management
- [ ] 7. Processor API
## Part III. ksqlDB
- [ ] 8. Getting Started with ksqlDB
- [ ] 9. Data Integration with ksqlDB
- [ ] 10. Stream Processing Basics with ksqlDB
- [ ] 11. Intermediate and Advanced Stream Processing with ksqlDB
## Part IV. The Road to Production
- [ ] 12. Testing, Monitoring, and Deployment
